# Generated by Django 3.1.7 on 2021-05-14 12:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес')),
                ('schedule', models.CharField(blank=True, max_length=50, null=True, verbose_name='Расписание')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_pics', verbose_name='Аватар')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+996XXXXXXXXX'.", regex='^\\+?1?\\d{12,15}$')], verbose_name='Телефон')),
                ('whats', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+996XXXXXXXXX'.", regex='^\\+?1?\\d{12,15}$')], verbose_name='Whatsapp')),
                ('insta', models.CharField(blank=True, max_length=31, null=True, validators=[django.core.validators.RegexValidator(regex='(^[A-Za-z0-9_](?:(?:[A-Za-z0-9_]|(?:\\.(?!\\.))){0,28}(?:[A-Za-z0-9_]))?)')], verbose_name='Instagram')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.status', verbose_name='subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('life_days', models.IntegerField(default=7, verbose_name='Срок действия (в днях)')),
                ('type', models.CharField(choices=[('register', 'Регистрация'), ('password_reset', 'Восстановление пароля')], default='register', max_length=20, verbose_name='Тип токена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аутентификационный токен',
                'verbose_name_plural': 'Аутентификационные токены',
            },
        ),
    ]
