# Generated by Django 3.1.7 on 2021-03-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='adress',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='profile',
            name='schedule',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Расписание'),
        ),
    ]
