# Generated by Django 3.1.7 on 2021-05-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210514_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='expired',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание вип статуса'),
        ),
    ]
