# Generated by Django 3.1.8 on 2021-05-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210514_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='up_counter',
            field=models.IntegerField(default=0, verbose_name='Количество апов'),
        ),
    ]
