# Generated by Django 3.1.7 on 2021-05-11 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210325_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='insta',
            field=models.CharField(blank=True, max_length=31, null=True, validators=[django.core.validators.RegexValidator(regex='(^[A-Za-z0-9_](?:(?:[A-Za-z0-9_]|(?:\\.(?!\\.))){0,28}(?:[A-Za-z0-9_]))?)')], verbose_name='Instagram'),
        ),
    ]
