FROM python:3.8.5 as build
ARG RUN_DB_MIGRATIONS_ARG=value
ENV RUN_DB_MIGRATIONS=$RUN_DB_MIGRATIONS_ARG
ENV PYTHONUNBUFFERED 1
RUN mkdir /usr/src/app/
WORKDIR /usr/src/app/
COPY requirements.txt /usr/src/app/
RUN pip install -r requirements.txt
COPY entrypoint.sh /usr/src/app/
RUN apt-get update && apt-get install --no-install-recommends -y netcat -V \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
RUN chmod +x  /usr/src/app/entrypoint.sh
COPY . /usr/src/app/
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
