# Generated by Django 3.1.7 on 2021-05-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210514_1905'),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
