# Generated by Django 3.1.8 on 2021-07-11 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='insta',
            field=models.CharField(blank=True, max_length=31, null=True, validators=[django.core.validators.RegexValidator(regex='(^[A-Za-z0-9_](?:(?:[A-Za-z0-9_]|(?:\\.(?!\\.))){0,28}(?:[A-Za-z0-9_]))?)')], verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+996XXXXXXXXX'.", regex='^\\+?1?\\d{12,15}$')], verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='item',
            name='whats',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+996XXXXXXXXX'.", regex='^\\+?1?\\d{12,15}$')], verbose_name='Whatsapp'),
        ),
    ]
