# Generated by Django 3.1.8 on 2021-05-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='viewed',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
