# Generated by Django 3.1.7 on 2021-05-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210511_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('Сом', 'Сом'), ('$', '$')], default='Сом', max_length=5, verbose_name='Валюта'),
        ),
    ]
