# Generated by Django 3.1.7 on 2021-05-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210512_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('Som', 'Сом'), ('$', '$')], default='Som', max_length=5, verbose_name='Валюта'),
        ),
    ]
